### PR TITLE
Allow both string and name type

### PR DESCRIPTION
**Pull request by kblais**
This PR allows the old syntax, and the syntax I suggested in #3 .

@mbardelmeijer can you tell me what you think about this ? I am open to any modification :)

### CODE REVIEW

**Comment by mbardelmeijer** [comment]
Oh wow, very cool! I'll take a look!

**Comment by mbardelmeijer** [comment]
Can you add a test for the name & string variants with a component that consists of 2 parts as well. For instance: `user-create`, and one for the nested variant suggested in #3, something like `table.user-search`?

Then we can ensure that behavior that we want in the end is checked by tests 👍 

Other than that, looking very good. Glad that we can merge this into the 1.x release cycle!

**Comment by kblais** [comment]
And here we go !

Those tests cover the 2 points to asked, just need a readme update (incoming)

**Comment by mbardelmeijer** [comment]
Awesome, thank you so much! I'll tag 1.2.0 in a bit.

**Pull request merged**
